# PSL.EmailService.Bus CI/CD pipeline

parameters:
  - name: buildConfig
    displayName: Build Configuration
    type: string
    default: Release
    values:
    - Debug
    - Release

resources:
  repositories:
  - repository: common
    type: git
    name: Hx/Hx.Common   

variables:
- template: pipelines/version.yml@common
# project level version numbers
- template: version-override.yml
# Local pipeline variables for use in common pipeline jobs

# Build Name is used in Helm appVersion so must follow SemVer spec
name: $[variables['chartVersion']]

trigger:
  batch: true
  branches:
    include: 
    - feature/* 
    - story/*
    - hotfix/* 
    - int
    - main
    - release/*
    - demo
  paths:
    exclude:
    - README.md

extends: 
  template: pipelines/template-default.yml@common
  parameters:
    buildConfiguration: ${{ parameters.buildConfig }}
    chartName: 'psl-microservicetemplate'
    dockerfile: 'src/PSL.MicroserviceTemplate.Api/Dockerfile'
    runtimeVersion: 6.0.x
    sonarCloudProjectKey: 'positivesolutions_PSL.MicroserviceTemplate'
    sonarCloudProjectName: 'PSL.MicroserviceTemplate'
    #    buildHelmOnBranch: true
