# Autoscaler for the API pod
{{- if .Values.autoscaler }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helpers.fullname" . }}
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "helpers.fullname" . }}
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
#    - type: Resource
#      resource:
#        name: memory
#        targetAverageUtilization: 80
{{- else }}
# Autoscaling disabled in values.yaml
{{- end }}