# ServiceAccount used by all Pods to access the Kubernetes API server
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helpers.serviceAccountName" . }}
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
  annotations:
