apiVersion: v1
kind: Service
metadata:
  name: {{ include "helpers.fullname" . }}
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
spec:
{{- if .Values.useLoadBalancer }}
  type: LoadBalancer
{{- else }}
  type: ClusterIP
{{- end }}
  selector:
    {{- include "helpers.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.servicePort | default 80 }}
    targetPort: {{ .Values.containerPort | default 80 }}    
    name: http
